FormApp/urls.py
from django.urls import path
from . import views

app_name = 'form_app'

urlpatterns = [
    path('insert_student', views.insert_student, name='insert_student'),
    path('students_list', views.students_list, name='students_list'),
    path('update_student/<int:id>', views.update_student, name='update_student'),
    path('delete_student/<int:id>', views.delete_student, name='delete_student'),
    path('insert_multiple_students', views.insert_multiple_students, name='insert_multiple_students')
]

FormExam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('form_app/', include('FormApp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FormApp/models.py
from django.db import models

# Create your models here.
class Students(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    grade = models.IntegerField()
    picture = models.FileField(upload_to='student/')

    class Meta:
        db_table = 'students'
        

FormApp/forms.py
from .models import Students
from django import forms


class StudentInsertForm(forms.ModelForm):

    name = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢')
    grade = forms.IntegerField(label='学年')
    picture = forms.FileField(label='ファイルアップロード', required=False)
    
    class Meta:
        model = Students
        fields = '__all__'


class StudentUpdateForm(forms.Form):
    name = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢')
    grade = forms.IntegerField(label='学年')
    picture = forms.FileField(label='ファイルアップロード')

class StudentDeleteForm(forms.Form):
    id = forms.IntegerField(widget=forms.HiddenInput)

FormApp/views.py
from django.shortcuts import render
from . import forms
from .models import Students
from django.core.files.storage import FileSystemStorage
import os
from django.forms import modelformset_factory
# Create your views here.


def insert_student(request):
    insert_form = forms.StudentInsertForm(request.POST or None, request.FILES or None)
    if insert_form.is_valid():
        insert_form.save()
        insert_form = forms.StudentInsertForm()
    return render(
        request, 'form_app/insert_student.html', context={
            'insert_form': insert_form
        }
    )

def students_list(request):
    students = Students.objects.all()
    return render(
        request, 'form_app/students_list.html', context={
            'students': students
        }
    )

def update_student(request, id):
    student = Students.objects.get(id=id)
    update_form = forms.StudentUpdateForm(
        initial = {
            'name': student.name, 'age': student.age, 'grade': student.grade, 'picture': student.picture
        }
    )
    if request.method == 'POST':
        update_form = forms.StudentUpdateForm(request.POST or None, request.FILES or None)
        if update_form.is_valid():
            student.name = update_form.cleaned_data['name']
            student.age = update_form.cleaned_data['age']
            student.grade = update_form.cleaned_data['grade']
            picture = update_form.cleaned_data['picture']
            if picture:
                fs = FileSystemStorage()
                file_name = fs.save(os.path.join('student', picture.name), picture)
                student.picture = file_name
            student.save()
    return render(
        request, 'form_app/update_student.html', context={
            'update_form': update_form,
            'student': student
        }
    )


def delete_student(request, id):
    delete_form = forms.StudentDeleteForm(
        initial={
            'id': id
        }
    )
    if request.method == 'POST':
        delete_form = forms.StudentDeleteForm(request.POST or None)
        if delete_form.is_valid():
            Students.objects.get(id=delete_form.cleaned_data['id']).delete()
        
    return render(
        request, 'form_app/delete_student.html', context={
            'delete_form': delete_form
        }
    )

def insert_multiple_students(request):
    StudentFormSet = modelformset_factory(Students, fields='__all__', extra=3)
    insert_form = StudentFormSet(request.POST or None, request.FILES or None)
    if insert_form.is_valid():
        insert_form.save()
    return render(
        request, 'form_app/insert_multiple_students.html', context={
            'insert_form': insert_form
        }
    )

templates/form_app/base.html
<!DOCTYPE html>
    <html>
        <head>
            <meta charset='utf-8'>
            <tile>{% block title %}DjangoForm{% endblock %}</title>
        </head>
        <body>
            <header>
                <a href="{% url 'form_app:insert_student' %}">メンバー追加</a>
                <a href="{% url 'form_app:students_list' %}">メンバー一覧</a>
                <a href="{% url 'form_app:insert_multiple_students' %}">メンバー一括追加</a>
            </header>
            {% block content %}{% endblock %}
        </body>
    </html>

templates/form_app/delete_student.html
{% extends "form_app/base.html" %}
{% block title %}メンバー削除画面{{ block.super }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ delete_form.as_p }}
    <input type = "submit" value="削除する">
</form> 

{% endblock %}

templates/form_app/insert_multiple_students.html
{% extends "form_app/base.html" %}
{% block title %}メンバー一括挿入画面{{ block.super }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ insert_form.as_p }}
    <input type = "submit" value="メンバー一括追加">
</form> 

{% endblock %}

templates/form_app/insert_student.html
{% extends "form_app/base.html" %}
{% block title %}メンバー挿入画面{{ block.super }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ insert_form.as_p }}
    <input type = "submit" value="メンバー追加">
</form> 

{% endblock %}

templates/form_app/students_list.html
{% extends "form_app/base.html" %}
{% block title %}メンバー一覧画面{{ block.super }}{% endblock %}
{% block content %}
<table>
    <tr>
        <th>名前</th>
        <th>年齢</th>
        <th>学年</th>
    </tr>
    {% for student in students %}
    <tr>
        <td><a href="{% url 'form_app:update_student' id=student.id %}">{{ student.name }}</a></td>
        <td>{{ student.age }}</td>
        <td>{{ student.grade }}</td>
    </tr>
    {% endfor %}
</table> 
{% endblock %}

templates/form_app/update_student.html
{% extends "form_app/base.html" %}
{% block title %}メンバー編集画面{{ block.super }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {{ update_form.as_p }}
    <input type = "submit" value="更新">
    <p><img src={{ student.picture.url }}></img></p>
</form> 
<p><a href="{% url 'form_app:delete_student' id=student.id %}">削除する</p>
{% endblock %}